### ISSUE TITLE
Spamhaus

### ISSUE THREAD

**Issue by Am11n** [EvotecIT/PSBlackListChecker#10]
I have used PSBlacklistchecker and found out that every Spamhaus.org is getting True (Blacklisted). When I use Mxtoolbox Im getting that it is false (Not Blacklisted).  Does somebody know why im getting this issue?

**Comment by PrzemyslawKlys** [comment]
There are multiple spamhous.org in blacklister - I think 4. On MxToolbox just 2. Without more details its hard to say why - it's a simple check in DNS you can do even manually.

**Comment by PrzemyslawKlys** [comment]
So I did some check some IP Address against my new module that checks blacklists and notice spamhaus is telling this IP has answer but if you check what answer actually means https://www.spamhaus.org/faqs/dnsbl-usage/#200

Return Code | Description
-- | --
127.0.0.0/24 | Spamhaus IP Blocklists
127.0.1.0/24 | Spamhaus Domain Blocklists
127.0.2.0/24 | Spamhaus Zero Reputation Domains list
127.255.255.0/24 | ERRORS (not implying a “listed” response)

Return Code | Zone | Description
-- | -- | --
127.0.0.2 | SBL | Spamhaus SBL Data
127.0.0.3 | SBL | Spamhaus CSS Data
127.0.0.4 | XBL | CBL Data
127.0.0.9 | SBL | Spamhaus DROP/EDROP Data (in addition to 127.0.0.2, since 01-Jun-2016)
127.0.0.10 | PBL | ISP Maintained
127.0.0.11 | PBL | Spamhaus Maintained


Return Code | Zone | Description
-- | -- | --
127.255.255.252 | Any | Typing error in DNSBL name
127.255.255.254 | Any | Query via public/open resolver
127.255.255.255 | Any | Excessive number of queries

The new module correctly does this assessment. I don't intend to fix this in PSBlacklistChecker as it will be archived, when the new module is out. 

```
IPAddress   FQDN                                      BlackList                     IsBlackListed Answer
---------   ----                                      ---------                     ------------- ------
96.48.74.89 96.48.74.89.b.barracudacentral.org        b.barracudacentral.org                 True 127.0.0.2
96.48.74.89 96.48.74.89.dnsbl.sorbs.net               dnsbl.sorbs.net                        True 127.0.0.10
96.48.74.89 96.48.74.89.safe.dnsbl.sorbs.net          safe.dnsbl.sorbs.net                   True 127.0.0.10
96.48.74.89 96.48.74.89.zen.spamhaus.org              zen.spamhaus.org                      False 127.255.255.254
96.48.74.89 96.48.74.89.xbl.spamhaus.org              xbl.spamhaus.org                      False 127.255.255.254
96.48.74.89 96.48.74.89.dbl.spamhaus.org              dbl.spamhaus.org                      False 127.255.255.254
96.48.74.89 96.48.74.89.sbl.spamhaus.org              sbl.spamhaus.org                      False 127.255.255.254
google.com  google.com.dbl.spamhaus.org               dbl.spamhaus.org                      False 127.255.255.254
96.48.74.89 96.48.74.89.cbl.abuseat.org               cbl.abuseat.org                       False 127.255.255.254
96.48.74.89 96.48.74.89.pbl.spamhaus.org              pbl.spamhaus.org                      False 127.255.255.254
google.com  google.com.hostkarma.junkemailfilter.com  hostkarma.junkemailfilter.com         False 127.0.0.3
96.48.74.89 96.48.74.89.hbl.spamhaus.org              hbl.spamhaus.org                      False
96.48.74.89 96.48.74.89.key.authbl.dq.spamhaus.net    key.authbl.dq.spamhaus.net            False
96.48.74.89 96.48.74.89.dnsbl.inps.de                 dnsbl.inps.de                         False
```
