### ISSUE TITLE
Tab auto-completion on -IP comes back as -IPs which does not match examples

### ISSUE THREAD

**Issue by jimpallomeni** [EvotecIT/PSBlackListChecker#3]
Tab auto-completion on -IP comes back as -IPs which does not match examples

**Comment by PrzemyslawKlys** [comment]
I have added -IP as alias to -IPS. Should fix your issue. Please verify and let me know. Generally both worked before due to how PowerShell allows you to not type whole parameter name but this one should make sure you can use tab auto-completion. 

https://github.com/EvotecIT/PSBlackListChecker/commit/61560bd199ab331797ec2bcae70d4f08a815cfc6

**Comment by jimpallomeni** [comment]
-IP and -IPs both worked before. Your readme examples shows -IP and would tab autocomplete shows -IPs which makes it a little confusing. I did an "update-Module PSBlackListChecker" and now both -IP and -IPs autocomplete so I would call it fixed. Thank you for the quick response.
